n = int(input("digite um nunero pra ver sua tabuada\n"))

print("-" * 12)
print("\033[4;31;44m {} X {} = {}".format(n,1,n*1))
print("{} X {} = {}".format(n,2,n*2))
print("{} X {} = {}".format(n,3,n*1))
print("{} X {} = {}".format(n,4,n*4))
print("{} X {} = {}".format(n,5,n*5))
print("{} X {} = {}".format(n,6,n*6))
print("{} X {} = {}".format(n,7,n*7))
print("{} X {} = {}".format(n,8,n*8))
print("{} X {} = {}".format(n,9,n*9))
print("{} X {} = {}".format(n,10,n*10))

print("-" * 12)